IDK

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -61,32 +61,44 @@ read_multiple_files(){
   #fi
 
   is_prev_date="false"
+  b_date_count=0
 for arg in "$@"
 do
   if [ "$is_prev_date" = "true" ]; then
     previous_date="$arg"
     is_prev_date="false"
       curr_arg=`expr $curr_arg + 1`
+      b_date_count=`expr $b_date_count + 1`
     
   fi
   if [ "$arg" = "-b" ]; then
     is_prev_date="true"
       curr_arg=`expr $curr_arg + 1`
   fi
+  if [[ $b_date_count -eq 2 ]]; then
+   >&2 echo "Too many -b" 
+   exit 1
+  fi
 done
 
   is_past_date="false"
+  a_date_count=0
 for arg in "$@"
 do
   if [ "$is_past_date" = "true" ]; then
     past_date="$arg"
     is_past_date="false"
       curr_arg=`expr $curr_arg + 1`
+      a_date_count=`expr $a_date_count + 1`
     
   fi
   if [ "$arg" = "-a" ]; then
     is_past_date="true"
       curr_arg=`expr $curr_arg + 1`
+  fi
+  if [[ $a_date_count -eq 2 ]]; then
+   >&2 echo "Too many -a" 
+   exit 1
   fi
 done
 
@@ -110,10 +122,10 @@ Options:
   -h, --help   - Display help with a brief description of each command and option.
 
 Examples:
-  $0 list -a 2023-12-31 23:59:59
-  $0 list-currency -c USD
-  $0 status -b 2023-11-01
-  $0 profit -c EUR"
+  $0 list -a 2023-12-31 23:59:59 Trader logfile.log
+  $0 list-currency -c USD Trader logfile.log
+  $0 status -b 2023-11-01 Trader logfile.log
+  $0 profit -c EUR Trader logfile.log"
   exit 0
 fi
 
@@ -123,11 +135,14 @@ if [ $# -le 1 ]; then
   exit 1
 fi
 # check validity of dates
-invalid_date=$(read_multiple_files "$@" | grep -v "\d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])*")
-if [ -z "$invalid_date" ]; then
-  exit 1
-fi
-
+#invalid_date=$(read_multiple_files "$@" | cut -d ';' -f2 | grep  "[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}")
+#echo "$invalid_date"
+#if [ ! -z "$invalid_date" ]; then
+#  exit 1
+#fi
+# row count check
+#invalid_row_count=$(read_multiple_files "$@" | awk -F';' 'NF!=4 || /^,|,$/{print "bad:", NR | "cat>&2"; exit 1}')
+#echo "$invalid_row_count"
 
 
 if [[ ("${!curr_arg}" == "list-currency")]]; then
